# Generated by Django 6.0 on 2025-12-17 07:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Full Stack Developer', max_length=100)),
                ('bio', models.TextField(default='Passionate developer creating amazing web experiences')),
                ('email', models.EmailField(default='example@email.com', max_length=254)),
                ('phone', models.CharField(default='+880 1234 567890', max_length=20)),
                ('location', models.CharField(default='Dhaka, Bangladesh', max_length=100)),
                ('profile_image_base64', models.TextField(blank=True, null=True)),
                ('profile_image_format', models.CharField(blank=True, max_length=10, null=True)),
                ('github', models.URLField(blank=True, default='https://github.com')),
                ('linkedin', models.URLField(blank=True, default='https://linkedin.com')),
                ('twitter', models.URLField(blank=True, default='https://twitter.com')),
                ('facebook', models.URLField(blank=True, default='https://facebook.com')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='Tech Company', max_length=100)),
                ('position', models.CharField(default='Software Developer', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('current', models.BooleanField(default=False)),
                ('description', models.TextField(default='Worked on various projects...')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiences', to='portfolio.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Awesome Project', max_length=200)),
                ('description', models.TextField(default='Project description goes here...')),
                ('image_base64', models.TextField(blank=True, null=True)),
                ('image_format', models.CharField(blank=True, max_length=10, null=True)),
                ('technologies', models.CharField(default='Django, React, PostgreSQL', max_length=200)),
                ('github_link', models.URLField(blank=True, default='https://github.com')),
                ('live_link', models.URLField(blank=True, default='https://example.com')),
                ('featured', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='portfolio.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Python', max_length=50)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps'), ('design', 'Design')], default='backend', max_length=20)),
                ('percentage', models.IntegerField(default=85)),
                ('color', models.CharField(default='#3498db', max_length=20)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='portfolio.profile')),
            ],
        ),
    ]
